version: 0.0
os: linux
files:
  - source: /primenumber.py
    destination: /usr/local/pythonapp
hooks:
  BeforeInstall:
    - location: scripts/removepython.sh
      timeout: 300
      runas: root
